version: '3.8'

services:
    db:
        platform: linux/arm64/v8
        image: mysql/mysql-server:8.0.23
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=bookstore
            - MYSQL_USER=user
        command: --lower_case_table_names=1

    web:
        build: .
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
